name: Update tides JSON daily

on:
  schedule:
    - cron: "0 4 * * *"   # elke dag om 04:00 UTC (~06:00 Belgische tijd in de zomer)
  workflow_dispatch:      # ook handmatig uitvoerbaar

permissions:
  contents: write   # nodig om terug te pushen naar de repo

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_tides.py

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data_tides.json
          git diff --cached --quiet || git commit -m "Update tides JSON [skip ci]"
          git push
